[CONFLICTS] Use `Jane_syntax` for `local_`, `global_`, etc.
This is the squashed form of commits
85c202c38fc15b054c8f45c68ea2d595332eb498..5738720f398f19acb1d7c73cb60de1d22dc6dc53,
whose individual commit messages are below, followed by rebasing onto `main`.

I'm committing the conflicts to hopefully make it possible to review the
resolution of the rebase.  We'll see how well this works.

----------

Add matches on `Jane_syntax.Core_type.of_ast`

Add the `local` extension, but don't use it yet

Power `local_` with the modular syntax (but not other modal things)

Power `global_` with the modular syntax machinery

Update the parser to use Jane syntax for `local_`; buggy w/ `global_`

Fix `Local.of_constr_arg`'s attribute handling

Update ocamlprof

Add constructor argument to `depend.ml`

Make `local_` in types contain more attributes

This lets us distinguish it from constructor arguments better

Correctly update attributes when matching on types/constructor args

Bootstrap

`make alldepend`

Fix printing bug for `local_`

Refactor attribute handling

This is a big change to `Jane_syntax_parsing`

Update passing tests

Add `Lexp_constrain_local`

Fix `local_` in patterns & the location of `local_` in expressions

Delete stray outdated comments

Move `exclave_` over to Jane syntax

Remove `extension.` options for `[@{non,}tail]`

Move curry-tracking over to Jane syntax

Reorder attribute addition for comprehensions

Rewrite the missed uses of `[%exclave]` to `exclave_`

Add some missing documentation

Make `Jane_syntax_parsing` no longer depend on `Misc`

Bootstrap

Update ocamlprof

Respond to simple parts of Nick's review

Formatting (and content) update for `Jane_syntax` example comments

Add test of attributes in `local_ (t[@a])`; currently handled wrong

Update: `get_alloc_mode` → `unwrap_mode`, document it, and fix a bug

Jane syntax constructor arguments don't come with attributes

Add missing invariant documentation

Handle locations for `local_` and `exclave_` without using `(); x`

Add some missing uses of `Location.ghostify`

Rework type of match_jane_syntax_piece

Add regression test (currently failing) for attribute handling

Respond to small pieces of @ncick-roberts's review

Remove `~attr` arguments from individual `Jane_syntax` extensions

More reponses to @ncick-roberts's review, including a bug fix

Fix `pprintast`'s handling of attributes on `let x = local_ e`

Fix bug with parenthesization of `local_`

Handle saving/restoring locations with `loc_stack`s

Minor review response

Remove `Embedded_name.marker_attribute_handler` machinery

Tweak `match_jane_syntax` (formerly `match_jane_syntax_piece`)

Make `save_location` and `restore_location` automatic

Reduce the parser diff

Per @riaqn, adjust the type of `check_eq_mode`; also, rename it

Added test demonstrating a bug in `Pprintast`

Currently, `Pprintast` does not print `global_` on tupled constructor fields
correctly, and instead crashes.

```
% cat test.ml; echo; _install/bin/ocamlc -dsource test.ml
type t = C of global_ string

type t =
  | C of
  File "test.ml", line 1, characters 14-21:
  1 | type t = C of global_ string
                    ^^^^^^^
  Error: Tried to restore a saved location here, but none were found.
```

This is a regression from the previous broken behavior of printing the attribute
literally:

```
% cat test.ml; echo; ocamlc -dsource test.ml
type t = C of global_ string

type t =
  | C of ((string)[@extension.global ])
```

The next commit will fix `Pprintast` to have the correct behavior

Fix printing of `global_` in tupled constructors

Switch from `%(%)` to `%t`