Fix issue with section attributes produced for `.debug_str`
The section attributes we were producing for the `.debug_str` section
were causing issues when using `clang` as an assembler. To reproduce
the bug, you can run:
```sh
export CC=clang
export CXX=clang++
export AS='clang -c'
autoconf
./configure --enable-dev --prefix=$PWD/_install
make -s -j $(nproc) && make -s install

echo 'let () = print_endline "Hello world";;' > example.ml
_build/default/boot_ocamlopt.exe -g -gno-upstream-dwarf example.ml
```

This was producing an error of the form:
```txt
/tmp/camlasm010433.s:8:2: error: changed section flags for .debug_str, expected: 0x30
        .section .debug_str,"",%progbits
        ^
/tmp/camlasm010433.s:8:2: error: changed section entsize for .debug_str, expected: 1
        .section .debug_str,"",%progbits
        ^
File "example.ml", line 1:
Error: Assembler error, input left in file /tmp/camlasm010433.s
```

This commit fixes this issue by setting the section flags and section entsize
to the expected values.